Additional Ports
typesafehub/conductr-doc pull request #277
Opened 2016-11-02 23:40 UTC by edwardcallahan

Adds additional peer port usage in 2.0.0

2016-11-02 23:40 UTC, edwardcallahan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure correct port mapping in install guide & migration guide](https://trello.com/c/N29Mj0Ly/378-ensure-correct-port-mapping-in-install-guide-migration-guide)

2016-11-02 23:48 UTC, fsat requested changes
I think we also need TCP 2552 to allow agents to talk to core:

https://github.com/typesafehub/conductr-ansible/pull/21/files

2016-11-02 23:53 UTC, edwardcallahan commented
Ah yes, added.

2016-11-03 06:13 UTC, huntc approved these changes

2016-11-03 06:13 UTC, merged