WIP - DON'T MERGE - Cd docs
typesafehub/conductr-doc pull request #304
Opened 2016-12-16 07:32 UTC by fsat

2016-12-16 07:32 UTC, fsat commented
Still wip, not yet done.

2016-12-16 07:33 UTC, fsat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document Continuous Delivery feature](https://trello.com/c/bE6ITw4w/442-document-continuous-delivery-feature)

2017-02-17 03:05 UTC, huntc requested changes

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/developer/ContinuousDeliverySetup.md
> +# Continuous Delivery Setup
This particular doc is really about publishing to bintray... not about CD setup...

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +From the perspective of Continuous Delivery setup, the ops are responsible for installation of the Continuous Delivery service of ConductR as well as configuration of Bintray webhook which communicat
`the operator`

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +conduct load continuous-delivery <path to generated bundle configuration>
Should you not substitute the `/tmp/cd-config` path that you used above instead?

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +
Is it not possible to verify that the webhook is working at this point in order to ensure that the setup is correct?

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +The `conduct deploy` command can be used to deploy a bundle manually through the Continuous Delivery pipeline.
We should first introduce this command by describing why it is useful i.e. to manually roll forward/back through deployments.

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/developer/ContinuousDeliverySetup.md
> +Continuous Delivery is a ConductR feature which allows bundles to deployed to a ConductR cluster upon being published to Bintray.
We should introduce what CD is and why the reader should care. Refer to Wikipedia perhaps, or extract from our original design doc. Also describe how CD works in the context of ConductR i.e. the rolling upgrade procedure. I find it quite exciting. Make mention of how we preserve bundle configurations containing sensitive data.

2017-02-17 03:05 UTC, huntc commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +Once a particular version has been selected for a production deployment, an operator can use `conduct deploy` command to promote this particular version into the production environment. Once the depl
This should be right at the top of the doc.

2017-02-17 06:33 UTC, fsat commented on src/main/play-doc/operation/ContinuousDeliverySetupOps.md
> +Once a particular version has been selected for a production deployment, an operator can use `conduct deploy` command to promote this particular version into the production environment. Once the depl
This is now moved after the CD intro

2017-02-17 06:37 UTC, huntc approved these changes

2017-02-17 06:37 UTC, merged

2017-02-17 06:43 UTC, fsat commented
#326 takes care of 2.0