Update the network setup to reflect topology update
typesafehub/conductr-doc pull request #305
Opened 2016-12-23 02:27 UTC by fsat

The topology update is as such:
- Use of 3 AZs as before.
- Subnets for public agent and private agent for each AZ.
- Security groups for public agent, private agent, and core node.
- Subnet and security group for bastion host.
- Updates to ELB security group.

2016-12-23 02:28 UTC, fsat commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a ConductR user, I want Lightbend Prod to be deployed on 2.0, so Lightbend can find issues before me.](https://trello.com/c/6lKCCRAF/412-as-a-conductr-user-i-want-lightbend-prod-to-be-deployed-on-2-0-so-lightbend-can-find-issues-before-me)

2016-12-28 19:38 UTC, edwardcallahan commented
Thanks for updating all the port mappings!

2017-01-05 19:34 UTC, edwardcallahan requested changes

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
Like the Ansible scripts, many should use the single SG 'flat' cluster to try ConductR in dev/test mode. The three SG model is less complicated and a better default. Can we do similar without making this super complicated?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +Create a subnet in the closest AZ. The bastion host will be hosted in this subnet, and thus only allowing SSH access from the outside world.
closest AZ doesn't make sense.

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +SG-ELB Outbound Rules
Why introduce outbound rules?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +#### Bastion Host Subnet and Security Group
Optional, no?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +Create a subnet in the closest AZ. The bastion host will be hosted in this subnet, and thus only allowing SSH access from the outside world.
Can we use public node subnets for the bastion w/ a bastion specific security group? IOW,  why do we want a new subnet for the single node?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +
If I am using public and private subnets don't I need one public and one private per AZ? Having core and private agents in a private subnet (outbound IGW access only) makes sense, but a single private SN per AZ is good for both, no? Of course if users have needs, but I'm not sure what the common user gains.

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +SG-AGENT-PUBLIC Inbound Rules
port 80? Isn't that what port I get with the hostname http endpoint?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +Our example subnets names indicate their AZ. In this case the subnet will be called SN-PUBLIC-A with a CIDR of `10.0.1.100/124`, SN-PRIVATE-B with a CIDR of `10.0.2.100/124`, and SN-PRIVATE-C with a
' SN-PRIVATE-C ' is incorrect here. What about creating all the subnets in one go? I don't like being bounced around w/in the console when following instructions.

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +Our example subnets names indicate their AZ. In this case the subnet will be called SN-PRIVATE-A with a CIDR of `10.0.1.0/49`, SN-PRIVATE-B with a CIDR of `10.0.2.0/49`, and SN-PRIVATE-C with a CIDR
Cool. This is what I expected.

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +SG-AGENT-PRIVATE Outbound Rules
Outbound rules. Still don't think we want them. I also presume we'd need a deny to activate?

2017-01-05 19:34 UTC, edwardcallahan commented on src/main/play-doc/operation/Install.md
> +Our example subnets names indicate their AZ. In this case the subnet will be called SN-PRIVATE-A with a CIDR of `10.0.1.0/49`, SN-PRIVATE-B with a CIDR of `10.0.2.0/49`, and SN-PRIVATE-C with a CIDR
A single IGW for all?

2017-01-12 12:50 UTC, huntc commented
@fsat can this be merged?

2017-01-27 17:35 UTC, merged

2017-01-27 21:50 UTC, huntc commented
Commit 1b8ec904ea7f5f555df412720404531fa5f3debf takes care of 2.0