Add information on OCI
typesafehub/conductr-doc pull request #357
Opened 2017-04-10 20:13 UTC by longshorej

This adds some information on creating OCI bundles and mentions OCI considerations for installation, release notes.

2017-04-12 21:36 UTC, longshorej commented
![](https://github.trello.services/images/mini-trello-icon.png) [Document OCI enhancements, being sure to link to doco from the release notes page](https://trello.com/c/2cGP9YRu/596-document-oci-enhancements-being-sure-to-link-to-doco-from-the-release-notes-page)

2017-04-17 00:52 UTC, huntc requested changes

2017-04-17 00:52 UTC, huntc commented on src/main/play-doc/developer/CreatingBundles.md
> +
I think we should go further here and recommend `openjdk/8-jre-alpine` as the base image to use.

(81.4MB in size)

2017-04-17 00:52 UTC, huntc commented on src/main/play-doc/operation/Install.md
> +Next, you'll need to configure a couple of settings in `conductr-agent.ini` and grant some privileges. ConductR uses [runc](https://runc.io/) to spawn and run OCI-based bundles. This requires the OCI
Elaborate on "why", and also how we've mitigated the risk side given that the root privilege is only granted to the script.

2017-04-17 21:48 UTC, longshorej commented on src/main/play-doc/developer/CreatingBundles.md
> +
Thanks - that's set.

2017-04-17 21:48 UTC, longshorej commented on src/main/play-doc/operation/Install.md
> +Next, you'll need to configure a couple of settings in `conductr-agent.ini` and grant some privileges. ConductR uses [runc](https://runc.io/) to spawn and run OCI-based bundles. This requires the OCI
This is set.

2017-04-17 23:05 UTC, huntc approved these changes

2017-04-17 23:06 UTC, merged