Beta.1 Release Notes
typesafehub/conductr-doc pull request #373
Opened 2017-05-18 08:27 UTC by huntc

... including a doc for external service discovery.

2017-05-18 15:27 UTC, markusjura requested changes
Overall, looking good. Only some minor comments.

2017-05-18 15:27 UTC, markusjura commented on src/main/play-doc/general/ReleaseNotes.md
> +As of 2.1, ConductR replaces the 2.0 mechanism with something considerably more flexible. Any service name may be registered via ConductR's configuration to exist as an external service, and one of:
`and one of: an explicit IP and port; DNS and port; or DNS SRV host may be supplied`

Can we create a separate bullet point for each item.

2017-05-18 15:27 UTC, markusjura commented on src/main/play-doc/general/ReleaseNotes.md
> +As of 2.1, ConductR replaces the 2.0 mechanism with something considerably more flexible. Any service name may be registered via ConductR's configuration to exist as an external service, and one of:
Also, it is possible to specify a set of URIs and not only one? The documentation does not point that out clearly enough.

2017-05-18 15:27 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +indicates the protocol to be used for connectivity. Additional fields include `authorization` which presently holds just `basic` reflecting HTTP basic authorization, along with correspondong `userinf
A table would be nice to list all required and optional response fields.

2017-05-19 07:16 UTC, huntc commented on src/main/play-doc/general/ReleaseNotes.md
> +As of 2.1, ConductR replaces the 2.0 mechanism with something considerably more flexible. Any service name may be registered via ConductR's configuration to exist as an external service, and one of:
Done

2017-05-19 07:23 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +indicates the protocol to be used for connectivity. Additional fields include `authorization` which presently holds just `basic` reflecting HTTP basic authorization, along with correspondong `userinf
Done

2017-05-19 07:37 UTC, markusjura requested changes
Requesting some styling changes.

2017-05-19 07:37 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +path             | The root context path to prepend to any other path in the case of HTTP.
The `path` is optional, right? If so we should mention that.

2017-05-19 07:37 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +Field            | Description
Can we order the fields either alphabetically or sorted by required and optional? I'd add the information to a field if it is required. So far we only describe that a given field is optional.

2017-05-19 07:37 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +## Receive hosts events (deprecated)
This API has been deprecated. We should describe what to use instead.

2017-05-19 07:37 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +## Find host service (deprecated)
This API has been deprecated. We should describe what to use instead.

2017-05-19 07:37 UTC, markusjura commented on src/main/play-doc/general/ReleaseNotes.md
> +* an explicit IP and port;
Semicolons, fullstops and or's should not be used in bullet points. Also, the first letter should be upper case. What about:

* IP address and port
* DNS address and port
* DNS SRV host

2017-05-19 07:38 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +Field            | Description
yes

2017-05-19 07:39 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +path             | The root context path to prepend to any other path in the case of HTTP.
yes - thanks

2017-05-19 07:39 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +## Receive hosts events (deprecated)
ok

2017-05-19 07:40 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +## Receive hosts events (deprecated)
done

2017-05-19 07:40 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +## Find host service (deprecated)
done

2017-05-19 07:40 UTC, huntc commented on src/main/play-doc/general/ReleaseNotes.md
> +* an explicit IP and port;
ok

2017-05-19 07:55 UTC, markusjura requested changes
- Mark required fields as required
- Links to deprecation replacement

2017-05-19 07:55 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +port             | The port to connect to.
We should document that port and protocol is a required field.

```
port             | The port to connect to. Required.
protocol         | The protocol to be used for connectivity. Required.
```

2017-05-19 07:55 UTC, markusjura commented on src/main/play-doc/api/BundleAPI.md
> +## Receive hosts events (deprecated - use the /v2 path instead)
Can we do more specific about the replacement and add a link to it, e.g.

## Receive hosts events (deprecated - use the [/v2](#Receive-hosts-events) endpoint instead)

The link consists of `[/v2](#Receive-hosts-events)`

Same for the other deprecated endpoints.

2017-05-19 08:02 UTC, huntc commented on src/main/play-doc/api/BundleAPI.md
> +port             | The port to connect to.
Presently consistent with other places.

2017-05-19 08:08 UTC, markusjura approved these changes

2017-05-24 03:45 UTC, merged